### PR TITLE
fix the glyphicons

### PR DESCRIPTION
**Pull request by sachinkiranti**
This PR resolved the glyph icons issues.

### CODE REVIEW

**Comment by sachinkiranti** [comment]
@Nix-code hi, do you not accept any PR right now ?

**Comment by nixhantb** [comment]
> @Nix-code hi, do you not accept any PR right now ?

Sorry, to mention that this is our college project and we are not able to accept any PR except the team members - If you want to contribute , please raise the issue mentioning the bugs

As soon as the college project evaluation will be completed, we will accept all the PRs and give credit to everyone for sure we will make this project even greater

**Comment by nixhantb** [comment]
> > @Nix-code hi, do you not accept any PR right now ?
> 
> Sorry, to mention that this is our college project and we are not able to accept any PR except the team members - If you want to contribute , please raise the issue mentioning the bugs
> 
> As soon as the college project evaluation will be completed, we will accept all the PRs and give credit to everyone for sure we will make this project even greater

Thanks @sachinkiranti  for the interest you have shown to this project, we will be noting your name and will give proper credit after the project evaluation will be done. We will record your PR for sure. Sorry for inconvenience.

**Comment by sachinkiranti** [comment]
Anytime @Nix-code Sorry I did not see anything mentioned about the college. Anyway best wishes :smile:  !

**Pull request closed without merging**
